### ISSUE TITLE
open public activitys via link causes an error

### ISSUE THREAD

**Issue by matzegebbe** [pump-io/pump.io#1022]
if i use 
https://io.intevation.de/mgebbe/activity/TXc9mhjPR9-ThBlD9_7WcQ
or 
https://identi.ca/seraphyn/activity/RjqcMuUzR-Ox0aWCVam73w

for example i got an error trace like that below. 
A public Activity should redirect to the note?

```
SyntaxError: Unexpected token :
    at Object.Function (<anonymous>)
    at Function._.template (/opt/pump.io/node_modules/utml/node_modules/underscore/underscore.js:1206:16)
    at Object.exports.compile (/opt/pump.io/node_modules/utml/utml.js:102:18)
    at Function.exports.compile (/opt/pump.io/node_modules/express/lib/view.js:68:33)
    at ServerResponse.res._render (/opt/pump.io/node_modules/express/lib/view.js:417:18)
    at ServerResponse.res.render (/opt/pump.io/node_modules/express/lib/view.js:318:17)
    at showActivity (/opt/pump.io/routes/web.js:316:13)
    at callbacks (/opt/pump.io/node_modules/express/lib/router/index.js:272:11)
    at Function.<anonymous> (/opt/pump.io/lib/objectmiddleware.js:174:21)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
```

**Comment by strugee** [comment]
We're releasing 1.0.0 tomorrow and this isn't in it. Pushing to 1.0.1
