### ISSUE TITLE
Error starting pump.io the first time

### ISSUE THREAD

**Issue by emanuelstanciu** [pump-io/pump.io#1263]
Hello, on first run I get the following. I tried a code search and the main error online without any luck. Anyone can think of something?
1|pump     | Error: setuid user id does not exist
1|pump     |     at Error (native)
1|pump     |     at Server.<anonymous> (/usr/lib/node_modules/pump.io/lib/app.js:499:25)
1|pump     |     at emitNone (events.js:91:20)
1|pump     |     at Server.emit (events.js:185:7)
1|pump     |     at emitListeningNT (net.js:1285:10)
1|pump     |     at _combinedTickCallback (internal/process/next_tick.js:71:11)
1|pump     |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
1|pump     | {"name":"pump.io","hostname":"IoT","pid":3938,"component":"cluster","level":40,"msg":"worker 4339 died (1). restarting...","time":"2017-01-14T17:32:59.531Z","v":0}

**Comment by emanuelstanciu** [comment]
wrong user in config file. typo, sorry
