### ISSUE TITLE
MongoError: $slice limit must be positive

### ISSUE THREAD

**Issue by stephensekula** [pump-io/pump.io#1287]
I am receiving the following error when retrieving the timeline with a client (e.g. like Dianara) and I'm not sure if this is a client-side issue or a server-side issue. Is anyone else seeing this?

MongoError: $slice limit must be positive
   at Function.MongoError.create (/home/pump/pump/pump.io.official/node_modules/databank/node_modules/mongodb-core/lib/error.js:31:11)
   at queryCallback (/home/pump/pump/pump.io.official/node_modules/databank/node_modules/mongodb-core/lib/cursor.js:197:34)
   at /home/pump/pump/pump.io.official/node_modules/databank/node_modules/mongodb-core/lib/connection/pool.js:455:18
   at _combinedTickCallback (internal/process/next_tick.js:67:7)
   at process._tickCallback (internal/process/next_tick.js:98:9)

I am running v2.1.1 of the server software.

Regards,
Steve

**Comment by strugee** [comment]
This has been reported on several servers. I used to think it was always a problem, but given the fact that this seems to have become pretty widespread in a pretty small window of time I'm now thinking it's probably a regression instead. I'll reprioritize this accordingly.

**Comment by stephensekula** [comment]
Very interesting! Glad to hear I'm not alone. I was having a hard time deciphering the origin of the problem.

**Comment by strugee** [comment]
@stephensekula yeah, it's a tricky one :/

**Comment by jankusanagi** [comment]
I'm still making sure, but the "slice thing" seems to happen when I fetch the "Meanwhile" or a timeline with a "since" parameter with Dianara, and 0 items are received because there's nothing new. If there are new items received, the error reply doesn't come.

**Comment by strugee** [comment]
I've narrowed this down to a regression in databank-mongodb 1.0.0. I need to bisect the bad patch and contact Evan, but in the meantime you can work around this by doing `npm install -g databank-mongodb@0.19.2` if you're on an npm-based install (recommended) or `npm install databank-mongodb@0.19.2` if you're on a source-based install.

**Comment by strugee** [comment]
https://github.com/e14n/databank-mongodb/commit/489016da1410c3c93ed6ed7f486193d9a78e91bb is the bad commit. I'm not sure if this is our problem or databank-mongodb's - it's possible that this is just exposing a bug that already existed in pump.io core. I doubt it, but it's worth checking.

**Comment by jankusanagi** [comment]
Good job! =)

**Comment by ian-kelling** [comment]
I got this too:

Fresh install, register user, click envelope icon on top then click all messages.

A banner pops in the web ui saying "500: Internal Server Error"

Network tab says 500 on loading http://localhost:5233/api/user/iank/inbox/direct/major?since=http%3A%2F%2Flocalhost%3A5233%2Fapi%2Factivity%2FEpre7iLXSAGYT5xDomg0jg

```
{"name":"pump.io","hostname":"li","pid":13802,"level":50,"err":{"message":"$slice limit must be positive","name":"MongoError","stack":"MongoError: $slice limit must be positive\n    at Function.MongoError.create (/usr/lib/node_modules/databank-mongodb/node_modules/mongodb-core/lib/error.js:31:11)\n    at queryCallback (/usr/lib/node_modules/databank-mongodb/node_modules/mongodb-core/lib/cursor.js:197:34)\n    at /usr/lib/node_modules/databank-mongodb/node_modules/mongodb-core/lib/connection/pool.js:461:18\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)","code":13100},"req":{"method":"GET","url":"/api/user/iank/inbox/direct/major?since=http%3A%2F%2Flocalhost%3A5233%2Fapi%2Factivity%2FKKTIES-rQDOmJooiwMzOPw","headers":{"host":"localhost:5233","connection":"keep-alive","accept":"application/json, text/javascript, */*; q=0.01","x-requested-with":"XMLHttpRequest","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36","authorization":"OAuth realm=\"OAuth\",oauth_version=\"1.0\",oauth_consumer_key=\"SYmgxfvKDgGYHJgiIR5JZQ\",oauth_token=\"6opkFW_ZhzgMh2CpfA7eaA\",oauth_timestamp=\"1491323086\",oauth_nonce=\"Ef7guT\",oauth_signature_method=\"HMAC-SHA1\",oauth_signature=\"4sia%2BnchS5croY2bIKP4JFpIc1c%3D\"","referer":"http://localhost:5233/main/messages","accept-encoding":"gzip, deflate, sdch, br","accept-language":"en-US,en;q=0.8","cookie":"connect.sid=s%3AVELvdT_x55xBA-CR2TelowO1bZCMaH7Q.nOm%2FdfWgRNmIuaplEMjUw7wAol9hMgouQSgmH0MWD5o"},"remoteAddress":"127.0.0.1","remotePort":44760},"msg":"$slice limit must be positive","time":"2017-04-04T16:24:46.590Z","v":0}
{"name":"pump.io","hostname":"li","pid":13802,"req_id":"44265176-610f-4af7-9774-1c9ac5f55d7d","component":"web","level":30,"req":{"method":"GET","url":"/api/user/iank/inbox/direct/major?since=http%3A%2F%2Flocalhost%3A5233%2Fapi%2Factivity%2FKKTIES-rQDOmJooiwMzOPw","headers":{"host":"localhost:5233","connection":"keep-alive","accept":"application/json, text/javascript, */*; q=0.01","x-requested-with":"XMLHttpRequest","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36","authorization":"OAuth realm=\"OAuth\",oauth_version=\"1.0\",oauth_consumer_key=\"SYmgxfvKDgGYHJgiIR5JZQ\",oauth_token=\"6opkFW_ZhzgMh2CpfA7eaA\",oauth_timestamp=\"1491323086\",oauth_nonce=\"Ef7guT\",oauth_signature_method=\"HMAC-SHA1\",oauth_signature=\"4sia%2BnchS5croY2bIKP4JFpIc1c%3D\"","referer":"http://localhost:5233/main/messages","accept-encoding":"gzip, deflate, sdch, br","accept-language":"en-US,en;q=0.8","cookie":"connect.sid=s%3AVELvdT_x55xBA-CR2TelowO1bZCMaH7Q.nOm%2FdfWgRNmIuaplEMjUw7wAol9hMgouQSgmH0MWD5o"},"remoteAddress":"127.0.0.1","remotePort":44760},"res":{"statusCode":500,"header":"HTTP/1.1 500 Internal Server Error\r\nX-Powered-By: Express\r\nServer: pump.io/4.0.0-alpha.0 express/4.15.2 node.js/v6.10.1\r\nContent-Security-Policy: default-src 'self'\r\nX-Frame-Options: DENY\r\nX-Download-Options: noopen\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: 697\r\nVary: Accept-Encoding\r\nDate: Tue, 04 Apr 2017 16:24:46 GMT\r\nConnection: keep-alive\r\n\r\n"},"serverTime":90,"principal":{"id":"http://localhost:5233/api/user/iank/profile","type":"person"},"client":{"key":"SYmgxfvKDgGYHJgiIR5JZQ","title":"pump.iankelling.org Web"},"msg":"","time":"2017-04-04T16:24:46.594Z","v":0}
MongoError: $slice limit must be positive
    at Function.MongoError.create (/usr/lib/node_modules/databank-mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/usr/lib/node_modules/databank-mongodb/node_modules/mongodb-core/lib/cursor.js:197:34)
    at /usr/lib/node_modules/databank-mongodb/node_modules/mongodb-core/lib/connection/pool.js:461:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at p
```rocess._tickCallback (internal/process/next_tick.js:104:9)

I'm using mongodb from debian 8, Version: 1:2.4.10-5.

**Comment by ian-kelling** [comment]
The workaround strugee posted above, https://github.com/pump-io/pump.io/issues/1287#issuecomment-286306392 is working for me.

**Comment by strugee** [comment]
FWIW I've also been in touch with Evan and we're working out a resolution to this :tada:
