### ISSUE TITLE
bcrypt upgrade is hosed

### ISSUE THREAD

**Issue by strugee** [pump-io/pump.io#1333]
Jason Self reports the following when installing 4.0.0 beta 4:

```
root@datamost:~# npm install -g pump.io@beta
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
/usr/bin/pump -> /usr/lib/node_modules/pump.io/bin/pump
/usr/bin/pump-authorize -> /usr/lib/node_modules/pump.io/bin/pump-authorize
/usr/bin/pump-follow -> /usr/lib/node_modules/pump.io/bin/pump-follow
/usr/bin/pump-post-note -> /usr/lib/node_modules/pump.io/bin/pump-post-note
/usr/bin/pump-register-app -> /usr/lib/node_modules/pump.io/bin/pump-register-app
/usr/bin/pump-register-user -> /usr/lib/node_modules/pump.io/bin/pump-register-user
/usr/bin/pump-stop-following -> /usr/lib/node_modules/pump.io/bin/pump-stop-following

> dtrace-provider@0.8.1 install /usr/lib/node_modules/pump.io/node_modules/dtrace-provider
> node scripts/install.js


> bcrypt@1.0.2 install /usr/lib/node_modules/pump.io/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@6.10.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/pump.io/node_modules/bcrypt/.node-gyp"
make: Entering directory '/usr/lib/node_modules/pump.io/node_modules/bcrypt/build'
make: *** No rule to make target '../.node-gyp/6.10.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/pump.io/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/pump.io/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/usr/lib/node_modules/pump.io/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /usr/lib/node_modules/pump.io/node_modules/bcrypt
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/pump.io/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/lib/node_modules/pump.io/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/pump.io/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/pump.io/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/pump.io/node_modules/bcrypt
node-pre-gyp ERR! node -v v6.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/pump.io/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/lib/node_modules/pump.io/node_modules/bcrypt/lib/binding' (1)
[               ...] \ install: info lifecycle bcrypt@1.0.2~install: Failed to exec install script
/usr/lib
└── (empty)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-04-07T16_28_00_804Z-debug.log
```

Obviously something went wrong with the bcrypt upgrade. We'll revert for now but long-term we need to deal with this.

**Comment by strugee** [comment]
Full npm log available at https://jxself.org/2017-04-07T16_28_00_804Z-debug.log.

**Comment by strugee** [comment]
INVALID now that #1233 has landed.
