### ISSUE TITLE
identi.ca users can't follow pump.iankelling.org users through the web ui

### ISSUE THREAD

**Issue by ian-kelling** [pump-io/pump.io#1639]
An identi.ca user reported this to me:

"after entering my identi.ca id in your server's remote login page, I get
redirected to
https://pump.iankelling.org/main/authorized/identi.ca?oauth_token=... and get
Internal Server Error"

I tried this same thing from a datamost.com account and it worked fine. My guess
is that identi.ca is running an old version.

I know identi.ca is just an instance, but a lot of the community is there and there is
no public issue tracker for it afaik.

pump.iankelling.org is running

commit 0bd61b1bace5227bbc13feb48068a4fbe0346a40
Date:   Sun May 6

**Comment by Serkan-devel** [comment]
Might be relevant here #1565

**Comment by strugee** [comment]
I'm confused - is 500 Internal Server Error coming from your node or from identi.ca? If it's from your node I'll need to see a stack trace from your logs.

**Comment by ian-kelling** [comment]
Yes, good point, my server is the important one in this case. Looks like this is the stack trace:

    TypeError: upstreamDuplicates is a object, not an array
        at /home/iank/pump.io/lib/model/activityobject.js:1117:23
        at arrayEach (/home/iank/pump.io/node_modules/lodash/lodash.js:537:11)
        at Function.forEach (/home/iank/pump.io/node_modules/lodash/lodash.js:9359:14)
        at Function.ActivityObject.validate (/home/iank/pump.io/lib/model/activityobject.js:1114:7)
        at Function.<anonymous> (/home/iank/pump.io/lib/model/activityobject.js:149:28)
        at next (/home/iank/pump.io/node_modules/step/lib/step.js:51:23)
        at next (/home/iank/pump.io/node_modules/step/lib/step.js:60:12)
        at Function.<anonymous> (/home/iank/pump.io/lib/model/activityobject.js:135:21)
        at next (/home/iank/pump.io/node_modules/step/lib/step.js:51:23)
        at Step (/home/iank/pump.io/node_modules/step/lib/step.js:122:3)

**Comment by ian-kelling** [comment]
this is duplicate of 801, i'm reposting it there

**Comment by ian-kelling** [comment]
Then we can close this.

**Comment by ian-kelling** [comment]
closing, duplicate of #801
