### ISSUE TITLE
TypeError when trying to start pump.io

### ISSUE THREAD

**Issue by CrazyJake88** [pump-io/pump.io#673]
Trying to start the pump.io script i get the following error.  I've been unable to find a solution and was told several others had this issue in the IRC channel.

ubuntu 12.04
nodejs v0.10.11
npm 1.2.30
mongodb

```
> pump.io@0.2.3 start /root/.npm/pump.io/0.2.3/package
> ./bin/pump

{"name":"pump.io","hostname":"convers","pid":27385,"component":"dispatch","level":30,"msg":"Dispatch setup complete.","time":"2013-06-17T16:48:19.550Z","v":0}
{"name":"pump.io","hostname":"convers","pid":27387,"level":30,"msg":"Initializing pump.io","time":"2013-06-17T16:48:19.943Z","v":0}

/root/.npm/pump.io/0.2.3/package/node_modules/databank/lib/databank.js:57
        canon = driver.toLowerCase(),
                       ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at Function.Databank.get (/root/.npm/pump.io/0.2.3/package/node_modules/databank/lib/databank.js:57:24)
    at makeApp (/root/.npm/pump.io/0.2.3/package/lib/app.js:131:19)
    at launchApps (/root/.npm/pump.io/0.2.3/package/bin/pump:100:9)
    at main (/root/.npm/pump.io/0.2.3/package/bin/pump:41:5)
    at Object.<anonymous> (/root/.npm/pump.io/0.2.3/package/bin/pump:131:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
{"name":"pump.io","hostname":"convers","pid":27388,"level":30,"msg":"Initializing pump.io","time":"2013-06-17T16:48:20.043Z","v":0}

/root/.npm/pump.io/0.2.3/package/node_modules/databank/lib/databank.js:57
        canon = driver.toLowerCase(),
                       ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at Function.Databank.get (/root/.npm/pump.io/0.2.3/package/node_modules/databank/lib/databank.js:57:24)
    at makeApp (/root/.npm/pump.io/0.2.3/package/lib/app.js:131:19)
    at launchApps (/root/.npm/pump.io/0.2.3/package/bin/pump:100:9)
    at main (/root/.npm/pump.io/0.2.3/package/bin/pump:41:5)
    at Object.<anonymous> (/root/.npm/pump.io/0.2.3/package/bin/pump:131:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
{"name":"pump.io","hostname":"convers","pid":27391,"level":30,"msg":"Initializing pump.io","time":"2013-06-17T16:48:20.157Z","v":0}

/root/.npm/pump.io/0.2.3/package/node_modules/databank/lib/databank.js:57
        canon = driver.toLowerCase(),
                       ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at Function.Databank.get (/root/.npm/pump.io/0.2.3/package/node_modules/databank/lib/databank.js:57:24)
    at makeApp (/root/.npm/pump.io/0.2.3/package/lib/app.js:131:19)
    at launchApps (/root/.npm/pump.io/0.2.3/package/bin/pump:100:9)
    at main (/root/.npm/pump.io/0.2.3/package/bin/pump:41:5)
    at Object.<anonymous> (/root/.npm/pump.io/0.2.3/package/bin/pump:131:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by ShijuDekhDekh1** [comment]
Hello All,

I am integrating pump.io in iOS development. I have created the server. But I am stuck with user registration/login process through the iOS app. I found the feeds, followers and following through this url:: https://hostname/api/user/nick name/feed

Trying to register in iOS mobile app: https://hostname/api/users/nickname=sam&password=sam

But bad luck. I don't know what i am missing? and please suggest me the registration process. So i can familiar with pump.io.

I found in the document of pump.io:

User registration

There is a collection of all users at the endpoint /api/users. To create a new user, POST a user representation (see below) to the list. You can also get the latest registered users by GETting the collection.

The JSON object representing the user has the following properties:

nickname: The user's nickname. 1-64 characters, including only ASCII capital and lowercase letters and numbers as well as ”-”, ”.”, and “_”. The nickname is immutable and unique per server; it can't be changed.
password: The plain-text password. This isn't returned when you GET the user object, but you have to provide it when registering or updating the user.
profile: a “person” object. This is created automatically when you create a new user; don't try to add it yourself. Don't update this directly; update the person through its object endpoint.

But don’t know how i integrate(Registration/Login process) in iOS App.

Regards
Shiju Varghese

**Comment by strugee** [comment]
@CrazyJake88 do you still need help? if not I'd like to close this issue.
