### ISSUE TITLE
Unable to upload avatar

### ISSUE THREAD

**Issue by llebegue** [pump-io/pump.io#713]
## Details
- Debian Wheezy
- Node.js 0.10.13 (installed from [Installing-Node.js-via-package-manager](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager) )
- pump.io version 0.2.3
## Graphic librairies installed 
- graphicsmagick 1.3.16
- imagemagick 6.7.7-10
- node : gm 1.10.0
## Configuration
- /etc/pump.io.json

```
{
    "driver":  "mongodb",
    "secret":  "secret",
    "noweb":  false,
    "site":  "Pump lebegue.org",
    "owner":  "",
    "ownerURL":  "https://pump.lebegue.org/",
    "port":  8000,
    "urlPort":  80,
    "hostname":  "pump.lebegue.org",
    "address":  "pump.lebegue.org",
    "nologger":  false,
    "serverUser":  "pump",
    "key_":  "/etc/ssl/private/lebegue_org_priv_key.pem",
    "cert_":  "/etc/ssl/certs/lebegue_org_public_certificate.pem",
    "uploaddir": "/home/www/pump/uploads",
    "debugClient": false,
    "firehose": "ofirehose.example"

}
```
## Log

```
{"name":"pump.io","hostname":"ks318403.kimsufi.com","pid":22874,"level":50,"err":{"message":"Cannot read property 'objectType' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'objectType' of undefined\n    at Activity.isMajor (/usr/local/lib/node
_modules/pump.io/lib/model/activity.js:1230:51)\n    at isMajor (/usr/local/lib/node_modules/pump.io/routes/api.js:242:18)\n    at callbacks (/usr/local/lib/node_modules/pump.io/node_modules/express/lib/router/index.js:272:11)\n    at sameUser (/usr/local/lib/node_modules
/pump.io/lib/middleware.js:75:9)\n    at callbacks (/usr/local/lib/node_modules/pump.io/node_modules/express/lib/router/index.js:272:11)\n    at Function.<anonymous> (/usr/local/lib/node_modules/pump.io/lib/middleware.js:63:17)\n    at next (/usr/local/lib/node_modules/pu
mp.io/node_modules/step/lib/step.js:51:23)\n    at Function.<anonymous> (/usr/local/lib/node_modules/pump.io/lib/model/activityobject.js:492:17)\n    at next (/usr/local/lib/node_modules/pump.io/node_modules/step/lib/step.js:51:23)\n    at /usr/local/lib/node_modules/pump
.io/node_modules/databank/lib/databankobject.js:110:33"},"msg":"Cannot read property 'objectType' of undefined","time":"2013-07-11T19:43:47.694Z","v":0}

```

**Comment by larjona** [comment]
Is this still a problem?

**Comment by rseabra** [comment]
It's an I sadly don't care anymore :(

**Comment by strugee** [comment]
Closing given the above statement. :(
