### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by ryanthejuggler** [pump-io/pump.io#741]
Every time I try to launch pump.io, I'm faced with the following error message:

```
-> % ./bin/pump
{"name":"pump.io","hostname":"pump","pid":2881,"component":"dispatch","level":30,"msg":"Dispatch setup complete.","time":"2013-07-15T21:06:53.025Z","v":0}
{"name":"pump.io","hostname":"pump","pid":2881,"component":"dispatch","level":30,"id":1,"msg":"Setting up worker.","time":"2013-07-15T21:06:53.031Z","v":0}
{"name":"pump.io","hostname":"pump","pid":2883,"level":30,"msg":"Initializing pump.io","time":"2013-07-15T21:06:53.446Z","v":0}
{"name":"pump.io","hostname":"pump","pid":2883,"level":30,"msg":"Connecting to databank with driver 'mongodb'","time":"2013-07-15T21:06:53.515Z","v":0}
{"name":"pump.io","hostname":"pump","pid":2883,"level":30,"msg":"Setting up HTTP server.","time":"2013-07-15T21:06:53.561Z","v":0}
{"name":"pump.io","hostname":"pump","pid":2883,"component":"sockjs","level":30,"msg":"Setting up sockjs server.","time":"2013-07-15T21:06:53.580Z","v":0}
{"name":"pump.io","hostname":"pump","pid":2883,"level":30,"firehose":"ofirehose.example.null","msg":"Setting up firehose","time":"2013-07-15T21:06:53.582Z","v":0}
{"name":"pump.io","hostname":"pump","pid":2883,"component":"firehose","firehose":"ofirehose.example.null","level":30,"msg":"Setting up firehose.","time":"2013-07-15T21:06:53.582Z","v":0}
{"name":"pump.io","hostname":"pump","pid":2883,"level":30,"msg":"Listening on 31337 for host pump.mydomain.net","time":"2013-07-15T21:06:53.583Z","v":0}

net.js:1055
    if (port && handle.getsockname && port != handle.getsockname().port) {
                      ^
TypeError: Cannot read property 'getsockname' of undefined
    at net.js:1055:23
    at Object.1:1 (cluster.js:587:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:339:9)
```

**Comment by strugee** [comment]
Closing for lack of activity. OP, if you still want help with this, then comment and I'll reopen. Otherwise, file a new issue.
