### ISSUE TITLE
Issues setting up with Appfog

### ISSUE THREAD

**Issue by bcomnes** [pump-io/pump.io#779]
I wanted to learn a bit more about pump.io, so I tried to deploy to Appfog following these instructions:
https://github.com/e14n/pump.io/wiki/Appfog

I tried to deploy the latest tag off of the github repository and ran into the following error:

```
Creating Application: OK
Creating Service [mongodb-pump]: OK
Binding Service [mongodb-pump]: OK
Uploading Application:
  Checking for available resources: OK
  Processing resources: OK
  Packing application: OK
  Uploading (997K): OK   
Push Status: OK
Staging Application 'pump': OK                                                  
Starting Application 'pump': .
Error: Application [pump] failed to start, logs information below.

====> /logs/stderr.log <====


node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /mnt/var/vcap.local/dea/apps/pump-0-3eb3f60e6f6f25f711a805b8b57d1c70/app/node_modules/bcrypt/build/Release/bcrypt_lib.node
    at Object..node (module.js:472:11)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at bindings (/mnt/var/vcap.local/dea/apps/pump-0-3eb3f60e6f6f25f711a805b8b57d1c70/app/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/mnt/var/vcap.local/dea/apps/pump-0-3eb3f60e6f6f25f711a805b8b57d1c70/app/node_modules/bcrypt/bcrypt.js:1:96)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)

```

Any ideas on what to do?  

UPDATE:
I tried the process again, this time using the zip of the tag instead of cloning.  It deployed the Appfog without error!  But then immediately crashed.  I'm getting the impression things have changed since the tutorial was written?

**Comment by strugee** [comment]
@bcomnes did you get installation to work?

**Comment by bcomnes** [comment]
Nah.  Gave up.  Just cleaning up old issues that I created. Feel free to reopen if its of any value still.
