### ISSUE TITLE
Pump.io errors when updating an object which has never been posted when no recipients are provided

### ISSUE THREAD

**Issue by erincandescent** [pump-io/pump.io#885]
If you update an object which hasn't been posted and don't specify a recipient list, Pump fails because it can't find the original post to extract the recipients from.

This should be more graceful - probably deliver the update to nobody?

11-24 03:29:42.157  22747-22813/eu.e43.impeller E/PostTask﹕ Error posting: Error: no original post
            at Function.<anonymous> (/opt/pump.io/lib/model/activity.js:899:30)
            at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
            at Function.<anonymous> (/opt/pump.io/lib/model/activity.js:1733:17)
            at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
            at Function.<anonymous> (/opt/pump.io/lib/model/activity.js:1704:21)
            at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
            at /opt/pump.io/node_modules/databank/lib/databankobject.js:131:35
            at /opt/pump.io/node_modules/databank/node_modules/databank-mongodb/lib/mongodb.js:511:33
            at /opt/pump.io/node_modules/databank/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:240:33
            at /opt/pump.io/node_modules/databank/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:658:35

**Comment by strugee** [comment]
We're releasing 1.0.0 tomorrow and this isn't in it. Pushing to a later release
