### ISSUE TITLE
Can't Update Group because it doesn't exist, can't Create Group because it already exists

### ISSUE THREAD

**Issue by hrdwdmrbl** [pump-io/pump.io#910]
That seems to be the pickle I'm in.

I send a message like

```
postJSON for  XXXXX {"verb":"create","to":[{"objectType":"collection","id":"http://activityschema.org/collection/public"}],"object":{"id":"tag:XXXXX.com,2013:project:XXXXX","objectType":"group","displayName":"XXXXX","summary":null,"XXXXX_com":{"subType":"project"}}}
Error from Pump.io: Internal Server Error status: 500
```

The error on pump.io is

```
Error: Already posted
at Function.Activity.applyPost.postExisting (/home/ubuntu/apps/Pump.io/releases/20131130223932/lib/model/activity.js:170:34)
at next (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/step/lib/step.js:51:23)
at Function.Activity.postOf (/home/ubuntu/apps/Pump.io/releases/20131130223932/lib/model/activity.js:1733:17)
at next (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/step/lib/step.js:51:23)
at Function.Activity.postOf.verbSearch (/home/ubuntu/apps/Pump.io/releases/20131130223932/lib/model/activity.js:1711:21)
at next (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/step/lib/step.js:51:23)
at DatabankObject.subClass.Cls.search (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/databank/lib/databankobject.js:131:35)
at bank.search (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/databank-mongodb/lib/mongodb.js:511:33)
at Cursor.each (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:240:33)
at Cursor.nextObject (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:658:35)
```

But, if I try to update the group:

```
postJSON for  XXXXX {"verb":"update","object":{"id":"tag:XXXXX.com,2013:project:XXXXX","objectType":"group","displayName":"XXXXX","summary":null}}
Error from Pump.io: Internal Server Error status: 500
```

The error from pump.io is:

```
Error: no original post
at Function.Activity.ensureRecipients.props (/home/ubuntu/apps/Pump.io/releases/20131130223932/lib/model/activity.js:899:30)
at next (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/step/lib/step.js:51:23)
at Function.Activity.postOf (/home/ubuntu/apps/Pump.io/releases/20131130223932/lib/model/activity.js:1733:17)
at next (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/step/lib/step.js:51:23)
at Function.Activity.postOf.verbSearch (/home/ubuntu/apps/Pump.io/releases/20131130223932/lib/model/activity.js:1711:21)
at next (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/step/lib/step.js:51:23)
at DatabankObject.subClass.Cls.search (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/databank/lib/databankobject.js:131:35)
at bank.search (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/databank-mongodb/lib/mongodb.js:511:33)
at Cursor.each (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:240:33)
at Cursor.nextObject (/home/ubuntu/apps/Pump.io/releases/20131130223932/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:658:35)
```

**Comment by ShijuDekhDekh1** [comment]
Hello,

I am integrating pump.io in iOS development. I have created the server. But I am stuck with user registration/login process through the iOS app. I found the feeds, followers and following through this url:: https://hostname/api/user/nick name/feed

Trying to register in iOS mobile app: https://hostname/api/users/nickname=sam&password=sam

But bad luck. I don't know what i am missing? and please suggest me the registration process. So i can familiar with pump.io.

I found in the document of pump.io:

User registration

There is a collection of all users at the endpoint /api/users. To create a new user, POST a user representation (see below) to the list. You can also get the latest registered users by GETting the collection.

The JSON object representing the user has the following properties:

nickname: The user's nickname. 1-64 characters, including only ASCII capital and lowercase letters and numbers as well as ”-”, ”.”, and “_”. The nickname is immutable and unique per server; it can't be changed.
password: The plain-text password. This isn't returned when you GET the user object, but you have to provide it when registering or updating the user.
profile: a “person” object. This is created automatically when you create a new user; don't try to add it yourself. Don't update this directly; update the person through its object endpoint.

But don’t know how i integrate(Registration/Login process) in iOS App.

Regards
Shiju Varghese
