### ISSUE TITLE
Can't get my "following" list -TypeError: Cannot read property 'id' of null-

### ISSUE THREAD

**Issue by nosecondtroy** [pump-io/pump.io#986]
Hi! I'm nosecondtroy [at] pumprock.net  
I can't get my "following" list, neither make person lists nor send posts to someone specific. 

When using the webUI, I get "500: Internal Server Error". Using the --debug mode on Dianara, I get the following trace: 

HTTP 500: Internal Server Error. 
Data:   "TypeError: Cannot read property 'id' of null
    at /opt/pump.io/lib/finishers.js:61:42
    at Array.map (native)
    at addFollowed (/opt/pump.io/lib/finishers.js:60:23)
    at /opt/pump.io/lib/streams.js:700:9
    at Function.collection.links.self.href.URLMaker.makeURL.offset (/opt/pump.io/lib/streams.js:250:17)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/opt/pump.io/node_modules/databank/lib/databankobject.js:238:21)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/opt/pump.io/node_modules/databank/lib/databankobject.js:218:21)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)"

**Comment by larjona** [comment]
Moved my pumpscripts to a new git hosting (since Gitorious is dead now): http://repo.or.cz/pumpscripts.git

**Comment by strugee** [comment]
This is moderately complex and we want to get 0.3.1 out fast; punting to 0.3.2
